use_frameworks!

platform :ios, '9.0'

target 'MachineLearnService_Example' do
  pod 'MachineLearnService', :path => '../'

  target 'MachineLearnService_Tests' do
    inherit! :search_paths

    
  end
end
